[tools]
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@openai/codex" = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:@withgraphite/graphite-cli" = "latest"
"npm:eas-cli" = "latest"
"npm:knip" = "latest"
"npm:neovim" = "latest"
"npm:taze" = "latest"
"npm:trash-cli" = "latest"
"npm:turbo" = "latest"
"npm:vercel" = "latest"
bun = "latest"
java = "24"
node = "22"
opencode = "latest"
pnpm = "10"
usage = "latest"
uv = "latest"
"npm:@google/gemini-cli" = "nightly"

[settings]
experimental = true
cargo_binstall = true
trusted_config_paths = ["~/Code/"]
vfox = false
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true

[env]
'_'.path = "~/bin"
OPENCODE_ENABLE_EXPERIMENTAL_MODELS = true
OPENCODE_EXPERIMENTAL_WATCHER = true
