[tools]
"github:code-yeongyu/go-claude-code-comment-checker" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:clawdbot" = "latest"
"npm:eas-cli" = "latest"
"npm:knip" = "latest"
"npm:neovim" = "latest"
"npm:ocx" = "latest"
"npm:opensrc" = "latest"
"npm:skills" = "latest"
"npm:taze" = "latest"
"npm:trash-cli" = "latest"
"npm:turbo" = "latest"
"npm:vercel" = "latest"
bun = "latest"
codex = "latest"
gemini = "latest"
graphite = "latest"
java = "24"
node = "24"
pnpm = "10"
usage = "latest"
uv = "latest"

[settings]
experimental = true
cargo_binstall = true
trusted_config_paths = ["~/Code/"]
vfox = false
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
package_manager = "bun"

[env]
'_'.path = "~/bin"
OPENCODE_EXPERIMENTAL = true
OPENSPEC_NO_AUTO_CONFIG = "1"
OPENSPEC_NO_COMPLETIONS = "1"
