[tools]
"amp" = "latest"
"github:code-yeongyu/go-claude-code-comment-checker" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:eas-cli" = "latest"
"npm:knip" = "latest"
"npm:neovim" = "latest"
"npm:taze" = "latest"
"npm:trash-cli" = "latest"
"npm:turbo" = "latest"
"npm:vercel" = "latest"
bun = "latest"
codex = "latest"
gemini = "latest"
graphite = "latest"
java = "24"
node = "24"
pnpm = "10"
usage = "latest"
uv = "latest"

[settings]
experimental = true
cargo_binstall = true
trusted_config_paths = ["~/Code/"]
vfox = false
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true

[env]
'_'.path = "~/bin"
OPENCODE_ENABLE_EXPERIMENTAL_MODELS = true
OPENCODE_EXPERIMENTAL_WATCHER = true
