gui:
  nerdFontsVersion: "3"
  mouseEvents: false
  showFileTree: true
  scrollHeight: 5
  expandFocusedSidePanel: false
git:
  localBranchSortOrder: recency
  pagers:
    - colorArg: always
    - pager: delta --dark --paging=never
  overrideGpg: true
  log:
    showWholeGraph: true
    showGraph: always
quitOnTopLevelReturn: false
os:
  editPreset: nvim
